---
title: "Exercise_05"
output: html_document
date: "2024-03-04"
---

```{r}

library("tidyverse")
library("dplyr")
library("mosaic")
library("ggplot2")
library("infer")
```

Challenge 1 Step 1


```{r}
f <- "https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/IMDB-movies.csv"
d <- read_csv(f, col_names = TRUE)
str(d)
```

Step 2

```{r}

d_2 <- d %>%
  filter(startYear <= 1979 & startYear >= 1920) %>%
  filter(runtimeMinutes >= 60 & runtimeMinutes <= 180) %>%
  mutate(decade = paste0((startYear - 1900) %/% 10 * 10, "s"))

str(d_2)
```

step 3
```{r}
p<-ggplot(d_2, aes(x=runtimeMinutes)) + 
  geom_histogram()+
  facet_wrap(~decade)
p
```
Step 4
```{r}
pop_var <- function(x) {
    sum((x - mean(x))^2)/(length(x))
}

```


```{r}
d_4 <- d_2 %>%
  group_by(decade) %>%
  summarise(pop_m = mean(runtimeMinutes), pop_sd = sqrt(pop_var(runtimeMinutes)))

d_4
```

Step 5


```{r}
d_5 <- d_2 %>%
  slice_sample(by = decade, n = 100) %>%
  group_by(decade)

(d_samp <- summarise(d_5, samp_m = mean(runtimeMinutes), samp_sd = sd(runtimeMinutes)))
```



Step 6
```{r}
d_6 <- d_5 %>%
  summarise(samp_se = sd(runtimeMinutes)/sqrt(n()))

d_6
```

Step 7


```{r}
d_7 <- d_2 %>%
  group_by(decade) %>%
  summarise(pop_se = sqrt(pop_var(runtimeMinutes)/100))
d_7
```

```{r}

(compare <- inner_join(inner_join(d_samp[1:2], d_4[1:2], by = "decade"), d_7, by = "decade"))
```
Step 8

```{r}
decades <- c(paste(2:7*10, "s", sep=""))

```

```{r}
samp_dist_for_decade <- function(decade) {
  d_decade <- d_2[d_2$decade== decade,]

  samp_dist <- d_decade %>%
    rep_sample_n(size = 100, reps = 1000, replace = FALSE) %>%
    group_by(replicate) %>%
    summarize(mean = mean(runtimeMinutes), sd=sd(runtimeMinutes)) %>%
    mutate(decade = decade)
  
  return(samp_dist)
}
samp_dist <- lapply(decades, samp_dist_for_decade)

 
All_samp_dist <- do.call(bind_rows, samp_dist)

```

Step 9
```{r}
samp_dist_stats_for_decade <- function(decade) {
  All_samp_dist_decade <- All_samp_dist[All_samp_dist$decade== decade,]

  samp_dist_stats <- All_samp_dist_decade %>%
    group_by(decade) %>%
    summarize(samp_dist_mean = mean(mean), samp_dist_se = sd(mean))
  
  return(samp_dist_stats)
}
samp_dist_stats <- lapply(decades, samp_dist_stats_for_decade)

 
(All_samp_dist_stats <- do.call(bind_rows, samp_dist_stats))

```

```{r}

p9 <-ggplot(All_samp_dist, aes(x=mean)) + 
  geom_histogram()+
  facet_wrap(~decade)
p9
```
The shape for each decade roughly follows the normal distribution curve

Step 10
```{r}
(compare10 <- inner_join(inner_join(d_6, d_7, by = "decade"), All_samp_dist_stats[c(1,3)], by = "decade"))
```




